### ISSUE TITLE
Where is the paper

### ISSUE THREAD

**Issue by Leerw** [dvlab-research/Stratified-Transformer#1]
Hi, thanks for your code repo, but the paper 'Stratified Transformer for 3D Point Cloud Segmentation' was not found on google, maybe it is not public yet now, could you please attach a PDF of that?

**Comment by X-Lai** [comment]
For the paper, please click https://mycuhk-my.sharepoint.com/personal/1155154502_link_cuhk_edu_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2F1155154502%5Flink%5Fcuhk%5Fedu%5Fhk%2FDocuments%2Fstratified%5Ftransformer%5Fcvpr2022%2Epdf&parent=%2Fpersonal%2F1155154502%5Flink%5Fcuhk%5Fedu%5Fhk%2FDocuments.

**Comment by Leerw** [comment]
thanks! but I have to right to access this link, please check it out.

**Comment by X-Lai** [comment]
The arXiv version is released.
