### ISSUE TITLE
Low training efficiency and warning "batch_size shortened from 8 to 1, points from 640000 to 80000."

### ISSUE THREAD

**Issue by LuZaiJiaoXiaL** [dvlab-research/Stratified-Transformer#11]
Hello!

Thanks for your great work. I tried to implement your code in my workstation.

I found that the max_batch_points and voxel_max were set to 140000 and 80000 in s3dis_stratified_transformer.yaml, respectively.

And batch_size was set to 8. In this case, the number of points in one batch can easily exceed 14w, say, the maximum is 8w*8=64w.

Maybe that's the reason why I often got this kind of warning,

"WARNING [main-logger]: batch_size shortened from 8 to 1, points from 640000 to 80000."

If I set the batch size to 1, the warning disappears, but less batch size brings more steps. Since I observed a low training speed per step, the overall training efficiency per epoch was poor with the whole S3DIS dataset. Do you have any suggestions to improve it?

I trained some other models like KPConv in my workstation. The training speed was higher and acceptable.

May I know whether the transformer model is relatively low in training efficiency? I am a layman in ML.

Cheers,

Eric.

**Comment by X-Lai** [comment]
Thanks for your interest in our work.

First, `max_batch_points` can be adjusted according to your hardware condition. These two arguments are set to avoid memory explosion. If you are using GPUs whose memory are more than 11G, you can set `max_batch_points` to a suitable value in your case as long as you have enough GPU memory. 

Second, the training speed of the self-attention operator is slower than the convolutional counterpart. But in our model, you can change the training epochs to 50 for quick training (the performance gap with 100 epochs would be within 1.0% mIoU).

Hope these can be helpful.

**Comment by LuZaiJiaoXiaL** [comment]
Thanks for your useful suggestions. Will have a try.

**Comment by yuchenlichuck** [comment]
Here is 1 A100 (80GB Memory) GPU's training warning:
`WARNING [04/20 14:40:43 main-logger]: batch_size shortened from 16 to 3, points from 901297 to 119988
WARNING [04/20 14:40:44 main-logger]: batch_size shortened from 16 to 3, points from 793041 to 114682
WARNING [04/20 14:40:45 main-logger]: batch_size shortened from 16 to 2, points from 1034501 to 136452
WARNING [04/20 14:40:49 main-logger]: batch_size shortened from 16 to 2, points from 1184282 to 120392
WARNING [04/20 14:40:49 main-logger]: batch_size shortened from 16 to 3, points from 853986 to 134254
WARNING [04/20 14:40:51 main-logger]: batch_size shortened from 16 to 2, points from 1089032 to 130792
WARNING [04/20 14:40:51 main-logger]: batch_size shortened from 16 to 1, points from 1023600 to 80000
WARNING [04/20 14:40:56 main-logger]: batch_size shortened from 16 to 2, points from 938096 to 113808
WARNING [04/20 14:40:56 main-logger]: batch_size shortened from 16 to 1, points from 1057780 to 66051
WARNING [04/20 14:40:58 main-logger]: batch_size shortened from 16 to 1, points from 839600 to 80000
WARNING [04/20 14:40:59 main-logger]: batch_size shortened from 16 to 1, points from 983264 to 72251
WARNING [04/20 14:41:04 main-logger]: batch_size shortened from 16 to 2, points from 1112184 to 123175
WARNING [04/20 14:41:05 main-logger]: batch_size shortened from 16 to 1, points from 1014559 to 63709
WARNING [04/20 14:41:06 main-logger]: batch_size shortened from 16 to 3, points from 887254 to 113941
WARNING [04/20 14:41:09 main-logger]: batch_size shortened from 16 to 2, points from 901949 to 124336
WARNING [04/20 14:41:11 main-logger]: batch_size shortened from 16 to 1, points from 983095 to 80000
WARNING [04/20 14:41:13 main-logger]: batch_size shortened from 16 to 2, points from 1020434 to 128505
WARNING [04/20 14:41:15 main-logger]: batch_size shortened from 16 to 3, points from 1044181 to 105055
WARNING [04/20 14:41:15 main-logger]: batch_size shortened from 16 to 2, points from 844335 to 135936
WARNING [04/20 14:41:16 main-logger]: batch_size shortened from 16 to 2, points from 854786 to 111498
WARNING [04/20 14:41:16 main-logger]: batch_size shortened from 16 to 3, points from 879924 to 112379
WARNING [04/20 14:41:19 main-logger]: batch_size shortened from 16 to 4, points from 952785 to 127065`

**Comment by X-Lai** [comment]
@yuchenlichuck So you can change the argument `max_batch_points` in the .yaml file to a much larger value.
