### ISSUE TITLE
RuntimeError: Caught an unknown exception!

### ISSUE THREAD

**Issue by faikit** [dvlab-research/Stratified-Transformer#16]
Hello, is there any hint for the cause of the problem?

```
  File "../lib/pointops2/functions/pointops.py", line 158, in forward
    pointops_cuda.attention_step1_forward_cuda_v2(N_k, M, h, C, n_max, q, k, index0_offsets, index1, output)
RuntimeError: Caught an unknown exception!
```

**Comment by X-Lai** [comment]
I haven't met this issue. Does it happen in the middle of training or at the beginning?

**Comment by faikit** [comment]
It's at the beginning, because i'm adapting ur model into another framework for my own task, so maybe a problem of compatibility. But the pointops2 is installed successfully, so still a little strange.

**Comment by X-Lai** [comment]
This function is tested to be correct on my side. You'd better check whether the input data does not align or they are in the cuda device, etc.
