### ISSUE TITLE
About the code realization of key sampling

### ISSUE THREAD

**Issue by whuhxb** [dvlab-research/Stratified-Transformer#17]
Hi, I have read through the code of stratified transformer, but I do not understand how to realize the key sampling with nearby points densely sampled and distant points sparsely sampled. How to realize and where? Thanks.

**Comment by X-Lai** [comment]
The function of `get_indice_pairs` implements key sampling. Please refer to [this line](https://github.com/dvlab-research/Stratified-Transformer/blob/main/model/stratified_transformer.py#L10).
