### ISSUE TITLE
some question about 'n_max'

### ISSUE THREAD

**Issue by Ultra11nstinct** [dvlab-research/Stratified-Transformer#22]
Hi @X-Lai ,
Thanks for the released code.

I am just wondering that why the 'n_max' need to be less than 1024, as you coded in class AttentionStep1_v2(Function). When I note the code 'assert n_max <= 1024', there will be an CUDA error: invalid configuration argument. (I think it is due to the limitation for 'n_max')

Sorry that I'm not familiar with CUDA C++ coding.
So, is there some solution to break the limitation for 'n_max'? Could you give me some advice?

It could be very nice that you leave me a email address, which could be convenient for discussion.
Here is mine: xiaoweili@stumail.ysu.edu.cn

Wish every success in your work.

**Comment by X-Lai** [comment]
Thanks for your interest in our work. We have the constraint of `n_max <= 1024` because the maximum threads of a CUDA thread block is 1024.

**Comment by Ultra11nstinct** [comment]
> 
Thanks for your reply, @X-Lai 
So is there any solution to break the limit?

**Comment by X-Lai** [comment]
The number of maximum threads is fixed for CUDA. For the cases where `n_max` larger than 1024, you'd better use the v1 version CUDA kernels in [here](https://github.com/dvlab-research/Stratified-Transformer/blob/main/lib/pointops2/functions/pointops.py#L82).

**Comment by Ultra11nstinct** [comment]
> The number of maximum threads is fixed for CUDA. For the cases where `n_max` larger than 1024, you'd better use the v1 version CUDA kernels in [here](https://github.com/dvlab-research/Stratified-Transformer/blob/main/lib/pointops2/functions/pointops.py#L82).

Got it.
Thanks for your reply and have a good day! :)
