### ISSUE TITLE
stratified_transformer.py, stratified calss , forward function inputs ?

### ISSUE THREAD

**Issue by RokiaAbdeen** [dvlab-research/Stratified-Transformer#27]
forward function for class Stratified takes these variables as input:
features, xyz, offset and batch
could you please explain what are these inputs refer to ? I wanna apply this architecture to a different computer vision task with different dataset, I know what are the features and xyz but what is offset? 

thank you so much in advance..

**Comment by X-Lai** [comment]
`features`:  the`rgb` color concatenated with `xyz` of all points. [N, 6]
`xyz`: the position of all points. [N, 3]
`offset`: each element indicates the location of a scene in the batch. [b]
`batch`: the index in the batch for each point. [N]

**Comment by tomanick** [comment]
@X-Lai , Thanks for your explanation. 
If the features do not contain xyz and they only have rgb color, is this OK?
Or it is better to concatenate rgb to xyz coordinates and make the input format of features become [N, 6] rather than [N, 3].

**Comment by RokiaAbdeen** [comment]
Sorry but these two variables are still unclear for me 
`offset: each element indicates the location of a scene in the batch. [b]
batch: the index in the batch for each point. [N]`
could you explain them again please
thank you..

**Comment by RokiaAbdeen** [comment]
are they a tensors? how about their shapes ? I got an error 
`clone() can't be used with integer or list`
