### ISSUE TITLE
RunTimeError: Caught an unknown exception

### ISSUE THREAD

**Issue by RokiaAbdeen** [dvlab-research/Stratified-Transformer#29]
I passed the following inputs to BasicLayer: 
feats.shape= [2,256,256] ,two batches each one has dimension 256*256 , I have reshaped them to size= [256,512]
xyz.shape=[2,3,256]  reshaped to [3,512]
each batch has two scenes, each scene has 256 points with 256 features for each one  size =[256,256]  for each scene (point cloud)
I putted the  offset =[256,512]  which means that the first point cloud ends at 256, the second at 512.
I got the following error in this line: 
`pointops_cuda.attention_step1_forward_cuda_v2`
![error](https://user-images.githubusercontent.com/26867350/174439431-09c1b18c-17b5-48e9-afa4-48d618df840a.png)
what would be the source of this error and how it might be resolved?
 thank you so much for your help ..

**Comment by X-Lai** [comment]
You should keep feats and xyz to the shape of [N, C] and [N, 3], respectively.

**Comment by RokiaAbdeen** [comment]
thank you for your reply
feats and xyz have shapes [N, C] and [N, 3] as you mentioned, but no v2 function works with me, all gives exception
still don't know where is the error..
