### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by whuhxb** [dvlab-research/Stratified-Transformer#3]
Hi:

    I have install the environment now, but I have met an error. I use one GPU in the .yaml file. I have met the following error.
Segmentation fault (core dumped)
    Have you ever met this error?

Best.

**Comment by X-Lai** [comment]
Can you report the error?

**Comment by whuhxb** [comment]
@X-Lai 
Hi, This is my error. Thanks.

srun -p RTXA6Kq -n 1 -w node12 python train.py --config config/s3dis/s3dis_stratified_transformer.yaml
srun: error: node12: task 0: Segmentation fault (core dumped)

**Comment by X-Lai** [comment]
It seems that the error comes from `srun`. I am not sure whether it is caused by the python task. Can you see which line of the python code causes this error?

**Comment by whuhxb** [comment]
@X-Lai 

No error line. When I run the command, this error occurs.

**Comment by whuhxb** [comment]
@X-Lai 
Both the s3dis_stratified_transformer.yaml and s3dis_swin3d_transformer.yaml meet the "Segmentation fault" error when starting to run.

**Comment by whuhxb** [comment]
@X-Lai 
I use srun because I run the code on a gpu cluster. My other programs can run with srun command, but when running your code this error occurs. I have no idea to solve this problem.

**Comment by X-Lai** [comment]
It seems the error does not come from the codes, since the code works on my side. It is hard to figure out where the error comes without any detailed error message.

**Comment by whuhxb** [comment]
@X-Lai 
Hi, what GPU resource are you using?

**Comment by whuhxb** [comment]
@X-Lai 
It seems that this error doesn't run within the python code.

**Comment by whuhxb** [comment]
@X-Lai 
I have printed line by line, it seems that the error occurs with util.voxelize.py  from torch_geometric.nn import voxel_grid. 
I have checked the version of torch_geometric, it is torch-geometric         1.7.2.

**Comment by X-Lai** [comment]
The version of torch-geometric is correct.

**Comment by yuchenlichuck** [comment]
it seems you the torch-geometric haven't been installed successfully
```
>>> import torch_geometric
Segmentation fault
```
