### ISSUE TITLE
Training stratified transformer on other datasets

### ISSUE THREAD

**Issue by LuZaiJiaoXiaL** [dvlab-research/Stratified-Transformer#33]
Hi, I have a question.

If I train this stratified transformer on my own dataset, what parameters should I change to achieve relatively good performance?

Best regards,

Eric

**Comment by X-Lai** [comment]
It depends on the points number and the xyz range of the scenes. Maybe the window_size and grid_size are important ones.

**Comment by LuZaiJiaoXiaL** [comment]
Thanks for your quick reply.

What do you mean by xyz range of the scenes?

Does the model have some specific requirements for the data? For example, coordinates of points should be recentered before feeding, and color must be set to 0-1 instead of 0-255?

I don't know whether they matter to the final performance.

Regards,

Eric.

**Comment by X-Lai** [comment]
Firstly, xyz range refers to the size of the room. You should adjust the `window_size` and `grid size` accordingly, because it can affect the receptive field of the model. 
Secondly, you may try it. I follow many previous works to do such normalization.
