### ISSUE TITLE
The stratified transformer with a shifted window

### ISSUE THREAD

**Issue by abc-def-g** [dvlab-research/Stratified-Transformer#35]
Thanks for the great work, it is very inspiring!

In the paper, you mention to apply the stratified transformer with a shifted window. But I cannot figure out the corresponding implementation in the released code. Could you please tell me where the shifted window is used in your code?

**Comment by X-Lai** [comment]
Please refer to [here](https://github.com/dvlab-research/Stratified-Transformer/blob/main/model/stratified_transformer.py#L306).

**Comment by abc-def-g** [comment]
Thanks!
