### ISSUE TITLE
can you share your dataset/s3dis/list/s3dis_names.txt and dataset/s3dis/list/val5_full.txt?

### ISSUE THREAD

**Issue by Qinerrrrr** [dvlab-research/Stratified-Transformer#39]

**Comment by Qinerrrrr** [comment]
Thanks.
I find I can run test.py without them.

**Comment by THHHomas** [comment]
@Qinerrrrr You can run the test without 'dataset/s3dis/list/s3dis_names.txt'? I encounter the error 'No such file or directory. ' Could you please tell me how to do it?
