### ISSUE TITLE
About conda list

### ISSUE THREAD

**Issue by aoligei178** [dvlab-research/Stratified-Transformer#4]
Hello! Thank you for your awesome work!
May I have a look at your conda list?

**Comment by X-Lai** [comment]
Here is the conda list for cuda11.1 (for running on RTX3090)

# packages in environment at /data/home/xinlai/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
addict                    2.4.0                    pypi_0    pypi
blas                      1.0                         mkl  
brokenaxes                0.4.2                    pypi_0    pypi
brotlipy                  0.7.0           py37h27cfd23_1003  
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8        py37h89c1867_1    conda-forge
cffi                      1.14.4           py37h261ae71_0  
chardet                   3.0.4           py37h06a4308_1003  
conda                     4.11.0           py37h89c1867_0    conda-forge
conda-package-handling    1.7.2            py37h03888b9_0  
cryptography              3.2.1            py37h3c74f83_1  
cudatoolkit               11.1.1               h6406543_8    conda-forge
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                      py_0    conda-forge
dominate                  2.6.0                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
freetype                  2.10.4               h5ab3b9f_0  
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
googledrivedownloader     0.4                pyhd3deb0d_1    conda-forge
idna                      2.10                       py_0  
intel-openmp              2020.2                      254  
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
joblib                    1.0.1                    pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
jsonpatch                 1.28                     pypi_0    pypi
jsonpointer               2.0                      pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
lame                      3.100             h7f98852_1001    conda-forge
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
libgfortran4              7.5.0               hae1eefd_17    conda-forge
libgomp                   9.3.0               h5101ec6_17  
libiconv                  1.16                 h516909a_0    conda-forge
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libtiff                   4.1.0                h2733197_1  
libuv                     1.42.0               h7f98852_0    conda-forge
lz4-c                     1.9.2                heb0550a_3  
markupsafe                2.0.1            py37h5e8e339_0    conda-forge
matplotlib                3.3.3                    pypi_0    pypi
mkl                       2020.2                      256  
mkl-service               2.3.0            py37he8ac12f_0  
mkl_fft                   1.2.0            py37h23d657b_0  
mkl_random                1.1.1            py37h0573a6f_0  
mmcv                      1.4.1                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
nettle                    3.6                  he412f7d_0    conda-forge
networkx                  2.5.1              pyhd8ed1ab_0    conda-forge
ninja                     1.10.2           py37hff7bd54_0  
numpy                     1.19.2           py37h54aff64_0  
numpy-base                1.19.2           py37hfa32c7d_0  
olefile                   0.46                     py37_0  
opencv-python             4.4.0.46                 pypi_0    pypi
openh264                  2.1.1                h780b84a_0    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.2.4                    pypi_0    pypi
pillow                    8.0.1            py37he98fc37_0  
pip                       20.3.1           py37h06a4308_0  
plyfile                   0.7.4                    pypi_0    pypi
protobuf                  3.14.0                   pypi_0    pypi
pycosat                   0.6.3            py37h27cfd23_0  
pycparser                 2.20                       py_2  
pyopenssl                 20.0.0             pyhd3eb1b0_1  
pyparsing                 2.4.7                    pypi_0    pypi
pysocks                   1.7.1                    py37_1  
python                    3.7.9                h7579374_0  
python-dateutil           2.8.1                    pypi_0    pypi
python-louvain            0.15               pyhd3deb0d_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.8.0           py3.7_cuda11.1_cudnn8.0.5_0    pytorch
pytorch-cluster           1.5.9           py37_torch_1.8.0_cu111    pyg
pytorch-scatter           2.0.8           py37_torch_1.8.0_cu111    pyg
pytorch-sparse            0.6.12          py37_torch_1.8.0_cu111    pyg
pytorch-spline-conv       1.2.1           py37_torch_1.8.0_cu111    pyg
pytorch_geometric         1.6.0              pyh9f0ad1d_0    <unknown>
pytz                      2021.1                   pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     20.0.0                   pypi_0    pypi
readline                  8.0                  h7b6447c_0  
requests                  2.25.0             pyhd3eb1b0_0  
ruamel_yaml               0.15.87          py37h7b6447c_1  
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
setuptools                51.0.0           py37h06a4308_2  
six                       1.15.0           py37h06a4308_0  
sklearn                   0.0                      pypi_0    pypi
sqlite                    3.33.0               h62c20be_0  
tensorboardx              2.1                      pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
tmux                      3.1                  ha1ba12b_0    conda-forge
torchaudio                0.8.0                      py37    pytorch
torchfile                 0.1.0                    pypi_0    pypi
torchvision               0.9.0                py37_cu111    pytorch
tornado                   6.1              py37h4abf009_0    conda-forge
tqdm                      4.54.1             pyhd3eb1b0_0  
typing_extensions         4.0.1              pyha770c72_0    conda-forge
unrar                     0.4                      pypi_0    pypi
urllib3                   1.25.11                    py_0  
visdom                    0.1.8.9                       0    conda-forge
websocket-client          0.57.0           py37hc8dfbb8_3    conda-forge
wheel                     0.36.1             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.6                      py_0    conda-forge
yaml                      0.2.5                h7b6447c_0  
yapf                      0.31.0                   pypi_0    pypi
zeromq                    4.3.3                h58526e2_3    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0

**Comment by X-Lai** [comment]
FYI, this conda list also works.

```
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
absl-py                   1.0.0                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.10.0                   pypi_0    pypi
blas                      1.0                         mkl  
bleach                    4.1.0                    pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.3.18            h06a4308_0  
cached-property           1.5.2                    pypi_0    pypi
cachetools                5.0.0                    pypi_0    pypi
certifi                   2021.10.8        py37h06a4308_2  
cffi                      1.15.0                   pypi_0    pypi
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.0.4                    pypi_0    pypi
configparser              5.2.0                    pypi_0    pypi
cudatoolkit               11.1.1               h6406543_8    conda-forge
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.6.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.6.0                    pypi_0    pypi
fonttools                 4.31.2                   pypi_0    pypi
freetype                  2.10.4               h0708190_1    conda-forge
gdown                     3.15.0                   pypi_0    pypi
gitdb                     4.0.9                    pypi_0    pypi
gitpython                 3.1.27                   pypi_0    pypi
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
google-auth               2.6.2                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
googledrivedownloader     0.4                      pypi_0    pypi
gql                       0.2.0                    pypi_0    pypi
graphql-core              1.1                      pypi_0    pypi
grpcio                    1.44.0                   pypi_0    pypi
h5py                      3.6.0                    pypi_0    pypi
hydra-core                0.11.3                   pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imageio                   2.15.0                   pypi_0    pypi
importlib-metadata        4.11.3                   pypi_0    pypi
importlib-resources       5.6.0                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
ipykernel                 6.9.2                    pypi_0    pypi
ipython                   7.32.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.7.0                    pypi_0    pypi
isodate                   0.6.1                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.1                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
jsonpatch                 1.32                     pypi_0    pypi
jsonpointer               2.2                      pypi_0    pypi
jsonschema                4.4.0                    pypi_0    pypi
jupyter-client            7.1.2                    pypi_0    pypi
jupyter-core              4.9.2                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-widgets        1.1.0                    pypi_0    pypi
kiwisolver                1.4.1                    pypi_0    pypi
lame                      3.100             h7f98852_1001    conda-forge
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libiconv                  1.16                 h516909a_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.0.9                he6b73bb_1    conda-forge
libuv                     1.42.0               h7f98852_0    conda-forge
llvmlite                  0.33.0                   pypi_0    pypi
markdown                  3.3.6                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.1                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.1            py37hd3c417c_0  
mkl_random                1.2.2            py37h51133e4_0  
nbclient                  0.5.13                   pypi_0    pypi
nbconvert                 6.4.5                    pypi_0    pypi
nbformat                  5.2.0                    pypi_0    pypi
ncurses                   6.3                  h7f8727e_2  
nest-asyncio              1.5.4                    pypi_0    pypi
nettle                    3.6                  he412f7d_0    conda-forge
networkx                  2.6.3                    pypi_0    pypi
ninja                     1.10.2               h4bd325d_0    conda-forge
notebook                  6.4.10                   pypi_0    pypi
numba                     0.50.1                   pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
nvidia-ml-py3             7.352.0                  pypi_0    pypi
oauthlib                  3.2.0                    pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
omegaconf                 1.4.1                    pypi_0    pypi
open3d                    0.10.0.0                 pypi_0    pypi
openh264                  2.1.1                h780b84a_0    conda-forge
openssl                   1.1.1n               h7f8727e_0  
packaging                 21.3                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.0.1                    pypi_0    pypi
pip                       21.2.2           py37h06a4308_0  
plyfile                   0.7.4                    pypi_0    pypi
pointops2                 0.0.0                    pypi_0    pypi
prometheus-client         0.13.1                   pypi_0    pypi
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.28                   pypi_0    pypi
protobuf                  3.19.4                   pypi_0    pypi
psutil                    5.9.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pygments                  2.11.2                   pypi_0    pypi
pyparsing                 3.0.7                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
python                    3.7.9                h7579374_0  
python-dateutil           2.8.2                    pypi_0    pypi
python-louvain            0.16                     pypi_0    pypi
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.8.0           py3.7_cuda11.1_cudnn8.0.5_0    pytorch
pytorch-cluster           1.5.9           py37_torch_1.8.0_cu111    pyg
pytorch-metric-learning   0.9.99                   pypi_0    pypi
pytorch-scatter           2.0.8           py37_torch_1.8.0_cu111    pyg
pytorch-sparse            0.6.12          py37_torch_1.8.0_cu111    pyg
pytz                      2022.1                   pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     22.3.0                   pypi_0    pypi
rdflib                    6.1.1                    pypi_0    pypi
readline                  8.1.2                h7f8727e_1  
requests                  2.27.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
scikit-image              0.16.2                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3            py37hc147768_0  
send2trash                1.8.0                    pypi_0    pypi
sentry-sdk                1.5.8                    pypi_0    pypi
setuptools                58.0.4           py37h06a4308_0  
sharedarray               3.2.1                    pypi_0    pypi
shortuuid                 1.0.8                    pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     5.0.0                    pypi_0    pypi
soupsieve                 2.3.1                    pypi_0    pypi
sqlite                    3.38.0               hc218d9a_0  
subprocess32              3.5.4                    pypi_0    pypi
tensorboard               2.8.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorboardx              2.5                      pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.13.3                   pypi_0    pypi
testpath                  0.6.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
timm                      0.5.4                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_0  
torch-geometric           1.7.2                    pypi_0    pypi
torch-points-kernels      0.6.10                   pypi_0    pypi
torch-points3d            1.3.0                    pypi_0    pypi
torchaudio                0.8.0                      py37    pytorch
torchfile                 0.1.0                    pypi_0    pypi
torchnet                  0.0.4                    pypi_0    pypi
torchvision               0.9.0                py37_cu111    pytorch
tornado                   6.1                      pypi_0    pypi
tqdm                      4.63.1                   pypi_0    pypi
traitlets                 5.1.1                    pypi_0    pypi
typing_extensions         4.1.1              pyha770c72_0    conda-forge
urllib3                   1.26.9                   pypi_0    pypi
visdom                    0.1.8.9                  pypi_0    pypi
wandb                     0.8.36                   pypi_0    pypi
watchdog                  2.1.7                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.3.1                    pypi_0    pypi
werkzeug                  2.0.3                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        3.6.0                    pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
zipp                      3.7.0                    pypi_0    pypi
zlib                      1.2.11               h7f8727e_4
```
