### ISSUE TITLE
Visualization Code

### ISSUE THREAD

**Issue by Qinerrrrr** [dvlab-research/Stratified-Transformer#41]
Could you share your visualization code please~
Thanks a lot.

**Comment by X-Lai** [comment]
Please refer to https://github.com/dvlab-research/Stratified-Transformer/issues/7.

**Comment by Qinerrrrr** [comment]
Thanks for your reply! I did not say it clearly. But I mean that how do you compare the pred with the label? I would be very grateful if you could show me some way.
