### ISSUE TITLE
The size of the attn_flat is [M, heads] , what is M ?

### ISSUE THREAD

**Issue by RokiaAbdeen** [dvlab-research/Stratified-Transformer#43]
In this part of code ,
`attn_flat = attn_flat + relative_position_bias #[M, num_heads]`
        
` softmax_attn_flat = scatter_softmax(src=attn_flat, index=index_0, dim=0) #[M, num_heads]`

could you please explain what is M here? thank you so much

**Comment by X-Lai** [comment]
M is the number of query-key pairs. For more detailed explanation, please refer to our paper.
