### ISSUE TITLE
INT_MAX error

### ISSUE THREAD

**Issue by L-Reichardt** [dvlab-research/Stratified-Transformer#44]
Hello,

I am encountering the following error, when using the model on larger pointclouds. I have reduced the model size and batch size, however I still get the following error.

```
index_0 = p2v_map.unsqueeze(-1).expand(-1, -1, k)[mask_mat] #[M, ]
RuntimeError: nonzero is not supported for tensors with more than INT_MAX elements,   file a support request
```

Do you know what causes this? I havent been able to find anything useful online.

**Comment by X-Lai** [comment]
It means that the number of query-key pairs is too large. You may consider setting a larger voxel_size.

**Comment by L-Reichardt** [comment]
Thank you for your answer. I thought maybe it points so something else, because the error I get following that is `RuntimeError: Caught an unknown exception!`

My model settings are : 
```
        dataset_dict = {
            'stem_transformer': True,
            'use_xyz': True,
            'sync_bn': False,
            'rel_query': True,
            'rel_key': True,
            'rel_value': True,
            'quant_size': 1.0, # 0.01
            'downsample_scale': 8,                          # Scale for Stratified window
            'num_layers': 1, # 2
            'patch_size': 1,
            'window_size': 8,
            'depths': [1, 1, 1, 1], # [2, 2, 6, 2]
            'channels': [32, 32, 32, 64],  # [48, 96, 192, 384]
            'num_heads': [4, 8, 16, 32], # [3, 6, 12, 24]
            'up_k': 3,
            'drop_path_rate': 0.3,
            'concat_xyz': False,
            'grid_size': 4.0, # 0.04
            'max_batch_points': 200000,
            'max_num_neighbors': 34, # 34
            'ratio': 0.25,                                  # Downsample ratio
            'k': 16, # 16
            'sigma': 1.0
            }
```

Basically I reduced the model to be as small as possible because the pointclouds I work with are so large I rather just get it running in a "minimum" configuration.

**Comment by L-Reichardt** [comment]
Update : Error disappears with 'stem_transformer' = False, so I guess there is an issue there

**Comment by X-Lai** [comment]
The error `RuntimeError: Caught an unknown exception!` is caused because you set the channel number per head to 8. Here we only support 16 or 32.

**Comment by X-Lai** [comment]
The parameters like `voxel_size` `quant_size` `grid_size` `max_batch_points` can be very important.

**Comment by L-Reichardt** [comment]
@X-Lai How exactly does quant_size relate to the voxels and grid sizes? What are the downsides of increasing the value?
