### ISSUE TITLE
ScanNet evaluation

### ISSUE THREAD

**Issue by LifeBeyondExpectations** [dvlab-research/Stratified-Transformer#51]
In table 2 of the manuscript, the authors present the results as `Val mIoU` and `Test mIoU`.
What specific data split did you use for training and evaluation?

e.g., 
`Val mIoU` = `train` (training) -> `val`(eval)
`Test mIoU` = `trainval` (training) -> `test`(eval)

**Comment by X-Lai** [comment]
Yes, you are right. For testing, we follow previous works to use both training and validation sets.
