### ISSUE TITLE
About Performance

### ISSUE THREAD

**Issue by aoligei178** [dvlab-research/Stratified-Transformer#53]
Thank you for your awesome work!
I found the mIOU on S3DIS Area5 in your official paper. Could you release your detailed results for each category? 
For instance: celling 98.2, wall, 99.5, clutter, 69.2 ... ...
Thanks a lot!

**Comment by X-Lai** [comment]
Please see our supplementary file: https://openaccess.thecvf.com/content/CVPR2022/supplemental/Lai_Stratified_Transformer_for_CVPR_2022_supplemental.pdf.
