### ISSUE TITLE
C/h template

### ISSUE THREAD

**Issue by kabouzeid** [dvlab-research/Stratified-Transformer#54]
Quick question, why did you decide to make `C/h` a template parameter rather than just passing it as a parameter to the func?

https://github.com/dvlab-research/Stratified-Transformer/blob/7b2a09218b4362db56a63d065a1e260c8deffd63/lib/pointops2/src/attention_v2/attention_cuda_kernel_v2.cu#L135-L144

**Comment by X-Lai** [comment]
Thank you for pointing out this issue. I am not sure whether it compiles well if we pass a division result as a template argument. If it compiles successfully, then feel free to modify it.

**Comment by kabouzeid** [comment]
What I meant was: why is this a template argument in the first place? Does this bring a significant performance improvement?

**Comment by X-Lai** [comment]
I don't really understand your question. `C/h` is just the dimension of each head. It is a hyper-parameter and usually set to the fixed 16.

**Comment by kabouzeid** [comment]
Sorry for the confusion. What I meant was if this brings a big runtime *speed* improvement, or why did you implement it that way? ie why do you have `template<d> void attention_step(...)` instead of just `void attention_step(..., d)`.

https://github.com/dvlab-research/Stratified-Transformer/blob/7b2a09218b4362db56a63d065a1e260c8deffd63/lib/pointops2/src/attention_v2/attention_cuda_kernel_v2.cu#L7-L10
