### ISSUE TITLE
Definition of some terms in config file

### ISSUE THREAD

**Issue by QasimKhan5x** [dvlab-research/Stratified-Transformer#68]
Can you please tell me the difference between the following parameters in the config file?

- `window_size` vs `grid_size`
- `grid_size` vs `voxel_max`

**Comment by X-Lai** [comment]
`window_size` means the size of window (here, 1 unit means a grid_size).
`grid_size` means the size of a grid (grid is similar to voxel, there is at most one point in a grid)
`voxel_max` means the maximum voxels / grids in an input scene.
