### ISSUE TITLE
No such file or directory: 'data/s3dis/s3dis_names.txt'

### ISSUE THREAD

**Issue by THHHomas** [dvlab-research/Stratified-Transformer#74]
When I run python test.py  --config config/s3dis/s3dis_stratified_transformer.yaml, I encounter the problem and I do not know where to get the s3dis_names.txt. 
As well as the 'dataset/s3dis/list/val5.txt' and 'dataset/s3dis/list/val5_full.txt', I do not know where to get. The original dataset do not contains the file and the processed file by pointnet2 also do not generate them. 
What shall I do.

**Comment by X-Lai** [comment]
Thank you very much for pointing out that. The `s3dis_names.txt` contains 
```
ceiling
floor
wall
beam
column
window
door
chair
table
bookcase
sofa
board
clutter
```

As for the `dataset/s3dis/list/val5.txt` and 'dataset/s3dis/list/val5_full.txt', actually we don't use them in `test.py`. So just ignore them.
