### ISSUE TITLE
K-sampling strategies

### ISSUE THREAD

**Issue by OPradelle** [dvlab-research/Stratified-Transformer#76]
Hi, thanks for sharing your work.

I have a question about the K-sampling strategies for the stratified version.
From what I understand, you compute attention weight for the query over the points set from the dense cloud with smaller windows and the low-density cloud with bigger windows.

However, I don't understand how do you apply those weights to the V vector. Does the V vector contain the encoded value for the denser and low density point set?

Thanks for your answer.

**Comment by X-Lai** [comment]
Yes, you are correct. The `V` vector contains the same number of tokens as the keys `K`, which is composed of both the denser and the sparser point set.
