### ISSUE TITLE
AssertionError when testing the pre-trained model s3dis_model_best.pth on S3DIS

### ISSUE THREAD

**Issue by ji-code25** [dvlab-research/Stratified-Transformer#77]
Firstly, thanks for your work on the Stratified-Transformer. 

When testing the pre-trained model s3dis_model_best.pth on S3DIS, the AssertionError of "assert (relative_position_index >= 0).all()" occurs. Since the pre-trained model was trained on S3DIS, running it on S3DIS should have been no problem. 

The following four steps are what I have done in testing the pre-trained model on S3DIS. 

**1. Download S3DIS of the version Stanford3dDataset_v1.2_Aligned_Version**

<img src="https://user-images.githubusercontent.com/5920304/210756076-5e9d3633-e7c4-4fce-8af0-09ad9da69ee6.png" width=450 height=150>

![s3dis_google_drive](https://user-images.githubusercontent.com/5920304/210756136-8d157bd8-8386-497b-87ea-411f2c8e199d.png)

**2. Preprocess the downloaded dataset to obtain .npy files**

<img src="https://user-images.githubusercontent.com/5920304/210773280-1ff96e30-0d00-4198-bdc3-fbd180d65abd.png" width=250 height=250>

**3. Modify the config file of config/s3dis/s3dis_stratified_transformer.yaml**

Change the data_root, model_path, and save_foler. Except those, I did not change other settings.

DATA:
  ....
  data_root: dataset/stanford_indoor3d 
  ...

TEST:
  ...
  model_path: pretrained/s3dis_model_best.pth
  save_folder: output/test/s3dis/stratified
  ...

**4. Testing**
I ran the command: python test.py --config config/s3dis/s3dis_stratified_transformer.yaml

![test_error](https://user-images.githubusercontent.com/5920304/210774085-87db6b54-1c39-47f5-bb17-dc7376953cb2.png)

Then, there is the AssertionError. I know it is due to the cRPE mechanism. 

Since the pre-trained model was trained on S3DIS, it would be no problem when tested on the same dataset. 

**Could you please point out in which step I am wrong? Many thanks!**

**Comment by ji-code25** [comment]
By debugging, after "test 1/7, 1/67, 20/65, 80000/236790", there will be a case that relative_position_index has one negative value: **relative_position_index[2842959] = tensor([-1,31,22])**, as shown below. 

<img src="https://user-images.githubusercontent.com/5920304/210804190-264e5fa4-d072-4130-899a-dbcdf233e37e.png">

<img src="https://user-images.githubusercontent.com/5920304/210804200-820ca2f7-0d5d-4ad4-9323-8d1ecfab82e1.png">

**Comment by ji-code25** [comment]
**More details.**
As shown in the previous comment, error_point_idx = 2842959. Then, 
xyz[index_0][error_point_idx] = [4.3200, 2.8800, 0.9320]
xyz[index_1][error_point_idx] = [4.6400, 2.8850, 1.0260]
, as shown in the below figures.

According to the #188 code, i.e., relative_position = xyz[index_0] - xyz[index_1]:
relative_position[error_point_idx] = [-0.3200, -0.0050, -0.0940]

According to the #189 code, i.e., relative_position = torch.round(relative_position * 100000) / 100000:
relative_position[error_point_idx] = [-0.3200, -0.0050, -0.0940]

Then, the #190 code, i.e., relative_position_index = (relative_position + 2 * self.window_size - 0.0001) // self.quant_size:
**relative_position_index[error_point_idx] = [-1, 31, 22], which will cause the AssertionError in #191 code.** 

<img src="https://user-images.githubusercontent.com/5920304/210856458-6d35a2ef-84c0-418a-9e0b-639069635afc.png" width=700 height=450>

<img src="https://user-images.githubusercontent.com/5920304/210856470-6c42ef4c-923c-447d-a2d9-c8d95c6d4330.png" width=700 height=450>

**Comment by ji-code25** [comment]
I changed the code for computing relative_position_index
from
&nbsp; relative_position_index = (relative_position + 2 * self.window_size - 0.0001) // self.quant_size
to
&nbsp; **relative_position_index = (relative_position + 2 * self.window_size) // self.quant_size**

**This time, the AssertionError is caused by the code: assert (relative_position_index <= 2*self.quant_grid_length - 1).all()**
, and error_point_idx = 5045428. Then, 
xyz[index_0][error_point_idx] = [4.6400, 2.8860, 1.1470]
xyz[index_1][error_point_idx] = [4.3200, 2.8800, 1.1460]
, as shown in the below figures.

According to the code, i.e., relative_position = xyz[index_0] - xyz[index_1]:
relative_position[error_point_idx] = [0.3200, 0.0060, 0.0010]

According to the code, i.e., relative_position = torch.round(relative_position * 100000) / 100000:
relative_position[error_point_idx] = [0.3200, 0.0060, 0.0010]

According to the modified code, i.e., relative_position_index = (relative_position + 2 * self.window_size) // self.quant_size:
**relative_position_index[error_point_idx] = [64, 32, 32], of which the first element exceed the upper bound 63** computed by 2 * self.quant_grid_length - 1. Thus, it will cause the AssertionError. 



<img src="https://user-images.githubusercontent.com/5920304/210869855-658a17d5-4252-4f26-98ad-a06312f446af.png" width=700 height=450>

<img src="https://user-images.githubusercontent.com/5920304/210869868-af99f60b-2e10-4aae-a3be-7088e39a7de0.png" width=700 height=450>

<img src="https://user-images.githubusercontent.com/5920304/210869872-b6952697-e155-4965-bf28-18d0cf8299e5.png" width=700 height=450>

**Comment by ji-code25** [comment]
In my opinion, the code for computing the relative_position_index:
&nbsp; &nbsp; relative_position_index = (relative_position + 2 * self.window_size - 0.0001) // self.quant_size
has a bug.

It can guarantee all the values of relative_position_index do not exceed the upper bound (63) **but cannot ensure that any of them is less than the lower bound (0)**. 

@X-Lai  Do you agree with the above tests and analysis?
Many thanks!

**Comment by X-Lai** [comment]
Thank you very much for pointing out this issue! You are correct. There is a bug.
