### ISSUE TITLE
computation complexity

### ISSUE THREAD

**Issue by yrk-creator** [dvlab-research/Stratified-Transformer#8]
I mentioned the code process the point cloud data by voxelize and sampling，it because the compute of transformer on point data is too large, but for test ,do you have better idea to predict all the raw point data at one time

**Comment by X-Lai** [comment]
For testing all points at one time, you can firstly voxelize the points, and then sample one point from each voxel to form a subsampled point cloud. Then, you can input this point cloud into the network for inference, and propagate each point to the original points in its corresponding voxels.

**Comment by yrk-creator** [comment]
OK, thank you, in this way propagating the original points to the original points is similar to the work of PointGroup.  right?  Hoping there will be more insteresting work in the later

**Comment by X-Lai** [comment]
Yes, thanks for your interest in our work.
