### ISSUE TITLE
Inconsistency between provided checkpoints and current model

### ISSUE THREAD

**Issue by databaaz** [dvlab-research/Stratified-Transformer#80]
The checkpoint file for Scannet (`scannet_model_best.pth`) has erroneous key names for the stem transformer layers.
While the model is defined with the prefixes `stem_layer....`, the corresponding weights in the checkpoint are labelled with keys `item_layer...`. 
This affects 7 such weights in the checkpoint

**Comment by X-Lai** [comment]
Yes, you're correct. It is because of a typo when I run the experiment. You just need to replace all the `item_layer` with `stem_layer` as https://github.com/dvlab-research/Stratified-Transformer/blob/main/test.py#L104.
