### ISSUE TITLE
No evaluation on Hallway_6 on S3DIS Area5

### ISSUE THREAD

**Issue by loicland** [dvlab-research/Stratified-Transformer#84]
Hi,

Thanks for the repo! It seems like there is an issue in [your evaluation](https://mycuhk-my.sharepoint.com/personal/1155154502_link_cuhk_edu_hk/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2F1155154502%5Flink%5Fcuhk%5Fedu%5Fhk%2FDocuments%2Fmodel%2Fs3dis%5Ftest%5Flog%2Etxt&parent=%2Fpersonal%2F1155154502%5Flink%5Fcuhk%5Fedu%5Fhk%2FDocuments%2Fmodel) of Fold 5 in S3DIS as you only infer on 67 rooms out of 68:  Hallway_6 is missing.

**Comment by X-Lai** [comment]
Yes, you're right. Thank you very much for pointing out this issue. We will fix this bug soon.
