### ISSUE TITLE
Supplementary documents on the paper

### ISSUE THREAD

**Issue by LiuDongzhen44** [dvlab-research/Stratified-Transformer#88]
First of all, thank you for your paper, but I couldn't find your documentation on shifted Windows，Can you provide it？

**Comment by X-Lai** [comment]
Sure, please find the supplementary material [here](https://openaccess.thecvf.com/content/CVPR2022/supplemental/Lai_Stratified_Transformer_for_CVPR_2022_supplemental.pdf).
